/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import DAO.TaiKhoanDAO;
import Entity.TaiKhoan;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author ASUS
 */
public class Account extends javax.swing.JPanel {

    private DefaultTableModel dtm = new DefaultTableModel();
private ArrayList<TaiKhoan> listTaiKhoan = new ArrayList<>();
private TaiKhoanDAO taiKhoanDAO = new TaiKhoanDAO();

    /**
     * Creates new form TaiKhoan
     */
   public Account() {
    initComponents();
    listTaiKhoan = (ArrayList<TaiKhoan>) taiKhoanDAO.selectAll();
     showData(listTaiKhoan);
    disabled();
}


    private void disabled() {
        txtEmail.setEnabled(false);
        txtTK.setEnabled(false);
        txtMK.setEnabled(false);
        txtMa.setEnabled(false);
        cbbLoaiTK.setEnabled(false);
        btnLuu.setEnabled(false);
        btnSua.setEnabled(false);
        btnXoa.setEnabled(false);
    }

    private void enabled() {
        txtEmail.setEnabled(true);
        txtTK.setEnabled(true);
        txtMK.setEnabled(true);
        txtMa.setEnabled(true);
        cbbLoaiTK.setEnabled(true);
        btnLuu.setEnabled(true);
        btnSua.setEnabled(true);
        btnXoa.setEnabled(true);
    }

    private void clear() {
        txtEmail.setText("");
        txtTK.setText("");
        txtMK.setText("");
        txtMa.setText("");
        cbbLoaiTK.setSelectedIndex(0);
    }

    private void showData(ArrayList<TaiKhoan> listTaiKhoan1) {
    dtm.setRowCount(0);
    for (TaiKhoan taiKhoan : listTaiKhoan) {
        dtm.addRow(taiKhoan.toDataRow());
    }
}


private void fillData(int index) {
    TaiKhoan t = listTaiKhoan.get(index);
    txtEmail.setText(t.getEmail());
    if (t.getLoaiTaiKhoan().equals("QL")) {
        cbbLoaiTK.setSelectedIndex(0);
    } else {
        cbbLoaiTK.setSelectedIndex(1);
    }
    txtMK.setText(t.getMatKhau());
    txtTK.setText(t.getTaiKhoan());
    txtMa.setText(t.getMaTk());
}


    private TaiKhoan getData() {
        TaiKhoan t = new TaiKhoan();
        if(txtMa.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this, "Mã tài khoản không được để trống");
            return null;
        }
        t.setMaTk(txtTK.getText());
        if(txtMa.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this, "Tài khoản không được để trống");
            return null;
        }
        t.setTaiKhoan(txtTK.getText());
        if(txtMK.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this, "Mật khẩu không được để trống");
            return null;
        }
        t.setMatKhau(txtMK.getText());
        if(txtEmail.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this, "Email tài khoản không được để trống");
            return null;
        }
        t.setEmail(txtEmail.getText());
        String loai = "QL";
        if (cbbLoaiTK.getSelectedItem().equals("QL")) {
            t.setLoaiTaiKhoan(loai);
        } else {
            loai = "NV";
            t.setLoaiTaiKhoan(loai);
        }
        return t;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblTaiKhoan = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtTK = new javax.swing.JTextField();
        txtMK = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        cbbLoaiTK = new javax.swing.JComboBox<>();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblTaiKhoan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblTaiKhoan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Tên nhân viên", "TK", "MK", "Email", "Loại TK"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTaiKhoanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTaiKhoan);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 191));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(49, 139, 130));
        jLabel1.setText("Mã NV");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 212, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(49, 139, 130));
        jLabel2.setText("TK");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 241, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(49, 139, 130));
        jLabel3.setText("MK");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(49, 139, 130));
        jLabel4.setText("Email");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, -1, -1));

        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 190, -1));

        txtTK.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(txtTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 238, 180, -1));

        txtMK.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(txtMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 267, 180, -1));

        btnThem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnThem.setForeground(new java.awt.Color(49, 139, 130));
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/add_28px.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        btnSua.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSua.setForeground(new java.awt.Color(49, 139, 130));
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/edit_28px.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, -1, -1));

        btnXoa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(49, 139, 130));
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Delete_28px.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, -1, -1));

        btnLuu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLuu.setForeground(new java.awt.Color(49, 139, 130));
        btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/save_28px.png"))); // NOI18N
        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });
        add(btnLuu, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(49, 139, 130));
        jLabel5.setText("Loại TK");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        txtMa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(txtMa, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 209, 180, -1));

        cbbLoaiTK.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "QL", "NV" }));
        add(cbbLoaiTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 130, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
       if (txtMa.getText().trim().equals("")) {
        JOptionPane.showMessageDialog(this, "Mã tài khoản không được để trống");
        return;
    }
    // Kiểm tra xem tài khoản có tồn tại không
            TaiKhoan existingTaiKhoan = taiKhoanDAO.selectById(txtMa.getText());
            if (existingTaiKhoan == null) {
           JOptionPane.showMessageDialog(this, "Không tìm thấy tài khoản có mã: " + txtMa.getText());
          return;
    }
             taiKhoanDAO.update(getData());
    // Hiển thị thông báo
         JOptionPane.showMessageDialog(this, "Tài khoản đã được cập nhật thành công.");
    // Cập nhật danh sách tài khoản
             listTaiKhoan = (ArrayList<TaiKhoan>) taiKhoanDAO.selectAll();
                      showData(listTaiKhoan);
    }//GEN-LAST:event_btnSuaActionPerformed

    private void tblTaiKhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTaiKhoanMouseClicked
        fillData(tblTaiKhoan.getSelectedRow());
    }//GEN-LAST:event_tblTaiKhoanMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        enabled();
        clear();
        btnLuu.setEnabled(true);
        btnXoa.setEnabled(true);
        btnSua.setEnabled(true);
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
       taiKhoanDAO.insert(getData()); // Phương thức này không trả về giá trị (kiểu void)
          JOptionPane.showMessageDialog(this, "Tài khoản đã được thêm vào."); // Hiển thị thông báo
         // Cập nhật danh sách tài khoản
           listTaiKhoan = (ArrayList<TaiKhoan>) taiKhoanDAO.selectAll();
          showData(listTaiKhoan);
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
  if (txtMa.getText().trim().equals("")) {
    JOptionPane.showMessageDialog(this, "Mã tài khoản không được để trống");
    return;
}
        List<TaiKhoan> listTaiKhoanDAO = null;

// Lấy mã tài khoản cần xóa từ danh sách hiện tại
           String maTaiKhoanCanXoa = listTaiKhoanDAO.get(tblTaiKhoan.getSelectedRow()).getMaTk();

// Thực hiện xóa tài khoản
           taiKhoanDAO.delete(maTaiKhoanCanXoa);
    JOptionPane.showMessageDialog(this, "Xóa tài khoản thành công");

// Cập nhật danh sách tài khoản
        listTaiKhoanDAO = taiKhoanDAO.selectAll();
        showData((ArrayList<TaiKhoan>) listTaiKhoanDAO);



    }//GEN-LAST:event_btnXoaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbbLoaiTK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTaiKhoan;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtMK;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtTK;
    // End of variables declaration//GEN-END:variables
}
