/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import DAO.HoaDonDAO;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class LichSuHoaDon extends javax.swing.JPanel {

    private HoaDonDAO hoaDonDAO = new HoaDonDAO(); // Tạo đối tượng HoaDonDAO

    /**
     * Creates new form LichSuHoaDon
     */
    public LichSuHoaDon() {
        initComponents();
        show();
    }

    public void show(String ngayBatDau, String ngayKetThuc) {
    List<Entity.HoaDon> hoaDonList;

    // Kiểm tra nếu ngày bắt đầu và ngày kết thúc khác null hoặc trống thì thực hiện tìm kiếm theo khoảng ngày
    if (ngayBatDau != null && !ngayBatDau.isEmpty() && ngayKetThuc != null && !ngayKetThuc.isEmpty()) {
        hoaDonList = hoaDonDAO.layDuLieuHoaDonDaThanhToanTrongKhoangNgay(ngayBatDau, ngayKetThuc);
    } else {
        // Nếu không có khoảng ngày, hiển thị tất cả dữ liệu
        hoaDonList = hoaDonDAO.layDuLieuHoaDonDaThanhToan();
    }

    Object[] obj = new Object[]{"Mã hóa đơn", "Nhân viên", "Khách hàng", "Ngày tạo", "Ngày thanh toán", "Khuyến mãi", "Tổng tiền", "Trạng thái", "Chú thích"};
    DefaultTableModel tableModel = new DefaultTableModel(obj, 0);
    tblLSHoaDon.setModel(tableModel);

    for (Entity.HoaDon hoaDon : hoaDonList) {
        Object[] item = new Object[9];
        item[0] = hoaDon.getMaHoaDon();
        item[1] = hoaDon.getMaNhanVien();
        item[2] = hoaDon.getTenKhachHang();
        item[3] = hoaDon.getNgayTao();
        item[4] = hoaDon.getNgayThanhToan();
        item[5] = hoaDon.getMaKhuyenMai();
        item[6] = hoaDon.getTongTien();
        item[7] = hoaDon.getTrangThai();
        item[8] = hoaDon.getGhiChu();
        tableModel.addRow(item);
    }
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLSHoaDon = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        txtNgay = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(49, 139, 130));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/iconBill.png"))); // NOI18N
        jLabel1.setText("LỊCH SỬ HÓA ĐƠN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(337, 337, 337)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(424, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 120));

        tblLSHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblLSHoaDon);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 1190, 520));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/search_28px.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 170, 90, 30));

        txtNgay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgayActionPerformed(evt);
            }
        });
        add(txtNgay, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 170, 150, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   // Lấy dữ liệu từ JTextField
String ngayString = txtNgay.getText();
// Định dạng ngày theo định dạng "yyyy-MM-dd"
SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

try {
    // Chuyển đổi các chuỗi ngày thành đối tượng Date
    Date date = sdf.parse(ngayString);
    // Format lại ngày thành chuỗi theo định dạng "yyyy-MM-dd"
    String formattedDate = sdf.format(date);
    // Gọi phương thức show1 với các giá trị đã định dạng
} catch (ParseException e) {
    // Xử lý nếu có lỗi khi chuyển đổi ngày
    e.printStackTrace();
}

    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtNgayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgayActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLSHoaDon;
    private javax.swing.JTextField txtNgay;
    // End of variables declaration//GEN-END:variables
}
