package views;

import DAO.DanhMucDAO;
import DAO.TaiKhoanDAO;
import Entity.DanhMuc;
import Helper.XDate;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author ASUS
 */
public class QLQuanLy extends javax.swing.JFrame {

    public String tenNV;
    Connection con = null;
    ResultSet rs = null;
    PreparedStatement ps = null;

    /**
     * Creates new form NewJFrame
     */
 public QLQuanLy(String tenNV) {
     this.tenNV = tenNV;
        initComponents();
        setTitle("QL cửa hàng bán Quần áo");

        // Thay thế các hoạt động liên quan đến cơ sở dữ liệu bằng DAO
        DanhMucDAO danhMucDAO = new DanhMucDAO();

        // Lấy danh sách DanhMuc từ cơ sở dữ liệu
        List<DanhMuc> listDanhMuc = danhMucDAO.selectAll();
          System.out.println("Danh sách DanhMuc có " + listDanhMuc.size() + " phần tử.");


        for (DanhMuc danhMuc : listDanhMuc) {
            // Thực hiện các thao tác cần thiết để hiển thị từng danh mục
            // Đây là nơi bạn sẽ cần thay đổi để phản ánh cấu trúc thực tế của đối tượng DanhMuc
            // và các thành phần liên quan trong giao diện người dùng của bạn.

            // Ví dụ: Thiết lập view (jpn và jlb) trực tiếp từ dữ liệu cơ sở dữ liệu
            // (Chú ý: Đây chỉ là một giả định, bạn cần cung cấp các phương thức thích hợp trong lớp DanhMucDAO)

            JPanel jpn = new JPanel(); // Thay thế bằng phương thức cụ thể trong lớp DanhMucDAO
            JLabel jlb = new JLabel(danhMuc.getTenDanhMuc()); // Thay thế bằng phương thức cụ thể trong lớp DanhMuc
            // Thêm sự kiện cho từng danh mục
            jpn.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    // Xử lý sự kiện khi một danh mục được chọn
                    // ...
             getContentPane().add(jpn);
             getContentPane().add(jlb);
                    // Ví dụ: Hiển thị thông tin của danh mục
                    System.out.println("Selected Category: " + danhMuc.getTenDanhMuc());
                }
            });
            // Thêm jpn và jlb vào giao diện của bạn (ví dụ: jpnMainPanel.add(jpn);)
        }
        setData();
        showName();
    }
 
 private void showName() {
    // Lấy thông tin tên nhân viên dựa trên tài khoản
    TaiKhoanDAO taiKhoanDAO = new TaiKhoanDAO();

    // Nếu tenNV chính là tài khoản, sử dụng nó trực tiếp
    String tenNhanVien = taiKhoanDAO.getTenNhanVienByTaiKhoan(tenNV);

    if (tenNhanVien != null) {
        txtTen.setText(tenNhanVien);
    }
}



private void setData() {
    // Hiển thị ngày hiện tại
    lblDate.setText(new SimpleDateFormat("dd/MM/yyyy").format(new java.util.Date()));

    // Bắt đầu luồng để cập nhật thời gian
    XDate xDate = new XDate(lblTime);
    Thread thread = new Thread(xDate);
    thread.start();

    // Cho phép hiển thị thời gian
    lblTime.setEnabled(true);
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnRoot = new javax.swing.JPanel();
        jpnMenu = new javax.swing.JPanel();
        jpnTrangChu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jlbTrangChu = new javax.swing.JLabel();
        jpnThucDon = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jlbThucDon = new javax.swing.JLabel();
        jpnBanHang = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jlbBanHang = new javax.swing.JLabel();
        jpnHoaDon = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jlbHoaDon = new javax.swing.JLabel();
        jpnDoanhThu = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jlbDoanhThu = new javax.swing.JLabel();
        jpnNhanVien = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jlbNhanVien = new javax.swing.JLabel();
        jpnKhuyenMai = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jlbKhuyenMai = new javax.swing.JLabel();
        jpnLSHoaDon = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jlbLSHoaDon = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblDate = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtTen = new javax.swing.JLabel();
        jpnTaiKhoan = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jlbTaiKhoan = new javax.swing.JLabel();
        jpnView = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpnMenu.setBackground(new java.awt.Color(51, 51, 51));
        jpnMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpnTrangChu.setBackground(new java.awt.Color(51, 51, 51));
        jpnTrangChu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/home23px.png"))); // NOI18N
        jpnTrangChu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 10, 30, 30));

        jlbTrangChu.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jlbTrangChu.setForeground(new java.awt.Color(255, 255, 255));
        jlbTrangChu.setText("Trang chủ");
        jpnTrangChu.add(jlbTrangChu, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 110, 50));

        jpnMenu.add(jpnTrangChu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 220, 50));

        jpnThucDon.setBackground(new java.awt.Color(51, 51, 51));
        jpnThucDon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/food.png"))); // NOI18N
        jpnThucDon.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 10, 30, 30));

        jlbThucDon.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jlbThucDon.setForeground(new java.awt.Color(255, 255, 255));
        jlbThucDon.setText("Sản phẩm");
        jpnThucDon.add(jlbThucDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 110, 50));

        jpnMenu.add(jpnThucDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 220, 50));

        jpnBanHang.setBackground(new java.awt.Color(51, 51, 51));
        jpnBanHang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/cart.png"))); // NOI18N
        jpnBanHang.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 10, 30, 30));

        jlbBanHang.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jlbBanHang.setForeground(new java.awt.Color(255, 255, 255));
        jlbBanHang.setText("Hóa đơn");
        jpnBanHang.add(jlbBanHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 110, 50));

        jpnMenu.add(jpnBanHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 220, 50));

        jpnHoaDon.setBackground(new java.awt.Color(51, 51, 51));
        jpnHoaDon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/bills_23px.png"))); // NOI18N
        jpnHoaDon.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 10, 30, 30));

        jlbHoaDon.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jlbHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        jlbHoaDon.setText("Thanh toán");
        jpnHoaDon.add(jlbHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 110, 50));

        jpnMenu.add(jpnHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 220, 50));

        jpnDoanhThu.setBackground(new java.awt.Color(51, 51, 51));
        jpnDoanhThu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Money_23px.png"))); // NOI18N
        jpnDoanhThu.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 10, 30, 30));

        jlbDoanhThu.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jlbDoanhThu.setForeground(new java.awt.Color(255, 255, 255));
        jlbDoanhThu.setText("Doanh thu");
        jpnDoanhThu.add(jlbDoanhThu, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 110, 50));

        jpnMenu.add(jpnDoanhThu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 220, 50));

        jpnNhanVien.setBackground(new java.awt.Color(51, 51, 51));
        jpnNhanVien.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/management_23px.png"))); // NOI18N
        jpnNhanVien.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 10, 30, 30));

        jlbNhanVien.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jlbNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        jlbNhanVien.setText("Nhân viên");
        jpnNhanVien.add(jlbNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 110, 50));

        jpnMenu.add(jpnNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 220, 50));

        jpnKhuyenMai.setBackground(new java.awt.Color(51, 51, 51));
        jpnKhuyenMai.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/sale.png"))); // NOI18N
        jpnKhuyenMai.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 10, 30, 30));

        jlbKhuyenMai.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jlbKhuyenMai.setForeground(new java.awt.Color(255, 255, 255));
        jlbKhuyenMai.setText("Khuyến Mãi");
        jpnKhuyenMai.add(jlbKhuyenMai, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 110, 50));

        jpnMenu.add(jpnKhuyenMai, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 220, 50));

        jpnLSHoaDon.setBackground(new java.awt.Color(51, 51, 51));
        jpnLSHoaDon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/bills_23px.png"))); // NOI18N
        jpnLSHoaDon.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 10, 30, 30));

        jlbLSHoaDon.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jlbLSHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        jlbLSHoaDon.setText("Lịch sử hóa đơn");
        jpnLSHoaDon.add(jlbLSHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 110, 50));

        jpnMenu.add(jpnLSHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 220, 50));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblDate.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblDate.setText("Date");

        lblTime.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblTime.setText("Time");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(49, 139, 130));
        jLabel6.setText("Giờ:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(49, 139, 130));
        jLabel12.setText("Ngày:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(49, 139, 130));
        jLabel13.setText("Tên NV:");

        txtTen.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtTen.setText("TênNV");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTime, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addComponent(lblDate, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addComponent(txtTen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtTen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDate)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTime)
                    .addComponent(jLabel6))
                .addContainerGap())
        );

        jpnMenu.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, -1));

        jpnTaiKhoan.setBackground(new java.awt.Color(51, 51, 51));
        jpnTaiKhoan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/acc.png"))); // NOI18N
        jpnTaiKhoan.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 10, 30, 30));

        jlbTaiKhoan.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jlbTaiKhoan.setForeground(new java.awt.Color(255, 255, 255));
        jlbTaiKhoan.setText("Tài khoản");
        jpnTaiKhoan.add(jlbTaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 110, 50));

        jpnMenu.add(jpnTaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 220, 50));

        javax.swing.GroupLayout jpnViewLayout = new javax.swing.GroupLayout(jpnView);
        jpnView.setLayout(jpnViewLayout);
        jpnViewLayout.setHorizontalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 978, Short.MAX_VALUE)
        );
        jpnViewLayout.setVerticalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpnRootLayout = new javax.swing.GroupLayout(jpnRoot);
        jpnRoot.setLayout(jpnRootLayout);
        jpnRootLayout.setHorizontalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnRootLayout.createSequentialGroup()
                .addComponent(jpnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnRootLayout.setVerticalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 729, Short.MAX_VALUE)
            .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnRoot, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(QLQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(QLQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(QLQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(QLQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new QLQuanLy().setVisible(true);
//            }
//        });
//    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jlbBanHang;
    private javax.swing.JLabel jlbDoanhThu;
    private javax.swing.JLabel jlbHoaDon;
    private javax.swing.JLabel jlbKhuyenMai;
    private javax.swing.JLabel jlbLSHoaDon;
    private javax.swing.JLabel jlbNhanVien;
    private javax.swing.JLabel jlbTaiKhoan;
    private javax.swing.JLabel jlbThucDon;
    private javax.swing.JLabel jlbTrangChu;
    private javax.swing.JPanel jpnBanHang;
    private javax.swing.JPanel jpnDoanhThu;
    private javax.swing.JPanel jpnHoaDon;
    private javax.swing.JPanel jpnKhuyenMai;
    private javax.swing.JPanel jpnLSHoaDon;
    private javax.swing.JPanel jpnMenu;
    private javax.swing.JPanel jpnNhanVien;
    private javax.swing.JPanel jpnRoot;
    private javax.swing.JPanel jpnTaiKhoan;
    private javax.swing.JPanel jpnThucDon;
    private javax.swing.JPanel jpnTrangChu;
    private javax.swing.JPanel jpnView;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel txtTen;
    // End of variables declaration//GEN-END:variables
}
